name: Docker Image CI

on:
  push:
    branches: [ "test-branch" ]
  pull_request:
    branches: [ "test-branch" ]


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
    
    - name: create package.json
      run: npm init -y

    - name: upload package.json to artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ./package.json 
  
   
