name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
    
    - name: create package.json
      run: npm init -y 
  
      
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: docker build -tag node-app:$(date +%s) . 
